// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd6Ld3Dpf4NiJVm48DAbpDShHmZucysSg',
    appId: '1:463247397082:web:619fff35edbbd8c90815e3',
    messagingSenderId: '463247397082',
    projectId: 'fir-setup-1f33d',
    authDomain: 'fir-setup-1f33d.firebaseapp.com',
    storageBucket: 'fir-setup-1f33d.appspot.com',
    measurementId: 'G-W58R18ELJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN_ry9hRuvJZfU8ZGdwS7cjg_2-BQehtc',
    appId: '1:463247397082:android:3b5889f7fce3bdcf0815e3',
    messagingSenderId: '463247397082',
    projectId: 'fir-setup-1f33d',
    storageBucket: 'fir-setup-1f33d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmkbUPIq-UItgKMF15n6KJUtt-75WZuXU',
    appId: '1:463247397082:ios:1a6b49125a6cb3490815e3',
    messagingSenderId: '463247397082',
    projectId: 'fir-setup-1f33d',
    storageBucket: 'fir-setup-1f33d.appspot.com',
    iosBundleId: 'com.tpapps.firebase_demo',
  );
}
